WITH
	T1 AS (
SELECT 
	'' AS POSITN_ID, POS.PARNT_TRADE_ID, POS.BUS_DT, POS.RUN_ID, POS.TRADE_ID, POS.SRC_SYS_CD,
	(CASE 
		WHEN POS.PARNT_TRADE_ID='<NA>' THEN POS.TRADE_ID
		ELSE POS.PARNT_TRADE_ID
	END) AS KEY_ID,
	(CASE 
		WHEN UPPER(POS.BUY_SELL)='SELL' THEN 'S'
		WHEN UPPER(POS.BUY_SELL)='BUY' THEN 'B'
	ELSE ''
	END) AS BUY_SELL,		POS.ASSET_CLASS AS PRODUCT_ID,
		POS.PRODUCT, UPPER(POS.OPT_TYPE) AS OPT_TYPE, POS.SA_NOTIONAL AS NOTIONAL,POS.SA_NOTIONAL AS UNITS, '1' AS CONTRACT_SIZE, 
		POS.STRIKE, POS.SACCR_CCY_CD AS STRIKE_CCY, POS.SUB_HEDGE_SET_TYPE AS REF_ENTITY_NAME, '' AS UNDRLY_SPOT_TKER,
		'' as SEC_SYMBOL, 
	(CASE 
		WHEN ASSET_SUB_CLASS='Index' THEN 'I'
		WHEN ASSET_SUB_CLASS='Single' THEN 'S'
	ELSE ''
	END) AS REF_TYPE,
	POS.PRICE AS REF_PRICE, POS.SACCR_CCY_CD AS REF_CCY, POS.SA_NOTIONAL AS MKT_NOTIONAL
FROM
	SA_CCR.LD_POSITN_CALCN_OVRD POS
WHERE
	POS.BUS_DT=TO_DATE(?, 'YYYY-MM-DD')
  AND POS.RUN_ID in (
                       select max(run_id)from sa_ccr.positn where bus_dt=to_date(?,'YYYY-MM-DD') and expr_run_id='99999999'
                       and SRC_SYS_CD ='IMAGINE'
                       and ASSET_CLASS in ('EQ','CR')
                       and POS.ASSET_SUB_CLASS<>'Index'
                       )
	AND POS.SRC_SYS_CD IN ('IMAGINE')
  AND POS.ASSET_CLASS in ('EQ','CR')
  AND POS.ASSET_SUB_CLASS<>'Index'

UNION

SELECT
	'' AS POSITN_ID, POS.PARNT_TRADE_ID, POS.BUS_DT, POS.RUN_ID, POS.TRADE_ID, POS.SRC_SYS_CD,
	(CASE
		WHEN POS.PARNT_TRADE_ID='<NA>' THEN POS.TRADE_ID
		ELSE POS.PARNT_TRADE_ID
	END) AS KEY_ID,
	(CASE
		WHEN UPPER(POS.BUY_SELL)='SELL' THEN 'S'
		WHEN UPPER(POS.BUY_SELL)='BUY' THEN 'B'
	ELSE ''
	END) AS BUY_SELL,	POS.ASSET_CLASS AS PRODUCT_ID,
		POS.PRODUCT, UPPER(POS.OPT_TYPE) AS OPT_TYPE, POS.SA_NOTIONAL AS NOTIONAL,POS.SA_NOTIONAL AS UNITS, '1' AS CONTRACT_SIZE,
		POS.STRIKE, POS.SACCR_CCY_CD AS STRIKE_CCY, POS.SUB_HEDGE_SET_TYPE AS REF_ENTITY_NAME, '' AS UNDRLY_SPOT_TKER,
		'' as SEC_SYMBOL,
	(CASE
		WHEN ASSET_SUB_CLASS='Index' THEN 'I'
		WHEN ASSET_SUB_CLASS='Single' THEN 'S'
	ELSE ''
	END) AS REF_TYPE,
	POS.PRICE AS REF_PRICE, POS.SACCR_CCY_CD AS REF_CCY, POS.SA_NOTIONAL AS MKT_NOTIONAL
FROM
	SA_CCR.LD_POSITN_CALCN_OVRD POS
WHERE
	POS.BUS_DT=TO_DATE(?, 'YYYY-MM-DD')
  AND POS.RUN_ID in (
                   select max(run_id)from sa_ccr.positn where bus_dt=to_date(?,'YYYY-MM-DD') and expr_run_id='99999999'
                   and SRC_SYS_CD ='SWAPONE'
                   and ASSET_CLASS in ('EQ','CR')
                   and POS.ASSET_SUB_CLASS<>'Index'
                   )
	AND POS.SRC_SYS_CD IN ('SWAPONE')
  AND POS.ASSET_CLASS in ('EQ','CR')
  AND POS.ASSET_SUB_CLASS<>'Index'

)SELECT
	T1.POSITN_ID, T1.BUS_DT, T1.RUN_ID, T1.TRADE_ID, T1.PARNT_TRADE_ID, T1.SRC_SYS_CD, T1.BUY_SELL,
	RPT.CPTY_CD, RPT.CPTY_LEGL_NAME, RPT.UEN, RPT.RSPNSBTY_CENTRE, RPT.TRANSIT, RPT.LEGL_ENTITY_CD,
	T1.PRODUCT_ID, T1.PRODUCT, T1.OPT_TYPE, T1.NOTIONAL, T1.UNITS, T1.CONTRACT_SIZE, T1.STRIKE, T1.STRIKE_CCY,
	T1.REF_ENTITY_NAME, T1.SEC_SYMBOL, T1.UNDRLY_SPOT_TKER, T1.REF_TYPE, T1.REF_PRICE, T1.REF_CCY,
	RPT.INSTM_TYPE, RPT.MTM, RPT.BSL_NOTIONAL, RPT.BSL_NOTIONAL_CCY_CD, RPT.SACCR_TRADE_NOTIONAL, RPT.BSL_ASSET_CLASS, RPT.CCP_IND
FROM T1
LEFT JOIN SA_CCR.RPT_CCBASEL_REPORT RPT
ON T1.KEY_ID=RPT.TRADE_ID AND T1.BUS_DT=RPT.BUS_DT AND T1.SRC_SYS_CD=RPT.SRC_SYS_CD
WHERE
  RPT.RUN_ID in (select max(run_id)from sa_ccr.rpt_ccbasel_report where bus_dt=to_date(?,'YYYY-MM-DD'))
  AND RPT.INTRNL_EXTR_IND='N'