select r.CPTY_CD,r.UEN,
(CASE
    WHEN UPPER(r.SACCR_ASSET_CLASS)= 'EQ' THEN 'EQ'
    WHEN UPPER(r.SACCR_ASSET_CLASS)in ('CRB','CRG') THEN 'CR'
    WHEN UPPER(r.SACCR_ASSET_CLASS)= 'FX' THEN 'FX'
    WHEN UPPER(r.SACCR_ASSET_CLASS)= 'IR' THEN 'IR'
    WHEN UPPER(r.SACCR_ASSET_CLASS)= 'CO' THEN 'CO'
    WHEN (UPPER(r.SACCR_ASSET_CLASS)= 'OT' OR UPPER(r.SACCR_ASSET_CLASS) is null) and UPPER(r.CONTRACT_TYPE)='INTRTE' THEN 'IR'
    WHEN (UPPER(r.SACCR_ASSET_CLASS)= 'OT' OR UPPER(r.SACCR_ASSET_CLASS) is null) and UPPER(r.CONTRACT_TYPE) in ('CRDRVB','CRDRVG') THEN 'CR'
    WHEN (UPPER(r.SACCR_ASSET_CLASS)= 'OT' OR UPPER(r.SACCR_ASSET_CLASS) is null) and UPPER(r.CONTRACT_TYPE)='EQLINK' THEN 'EQ'
    WHEN (UPPER(r.SACCR_ASSET_CLASS)= 'OT' OR UPPER(r.SACCR_ASSET_CLASS) is null) and UPPER(r.CONTRACT_TYPE)='FXGOLD' THEN 'FX'
    WHEN (UPPER(r.SACCR_ASSET_CLASS)= 'OT' OR UPPER(r.SACCR_ASSET_CLASS) is null) and UPPER(r.CONTRACT_TYPE)='OTHCOM' THEN 'CO'
  ELSE 'OT'
END) AS SACCR_ASSET_CLASS,
(NVL(r.CCP_VARITN_MRGN_POSTD,0)+r.MTM) AS MTM,
r.BSL_NOTIONAL as NOTIONAL, r.BSL_NOTIONAL_CCY_CD, r.NETG_SET_ID, r.CCP_VARITN_MRGN_RECVD,
r.CCP_VARITN_MRGN_POSTD, r.VARITN_MRGN_CCY_CD, r.EXPSR_TYPE
from SA_CCR.RPT_CCBASEL_REPORT r
where r.bus_dt=TO_DATE(?, 'YYYY-MM-DD') and r.RUN_ID in (select max(run_id)from SA_CCR.RPT_CCBASEL_REPORT where bus_dt=TO_DATE(?, 'YYYY-MM-DD'))
and (r.CCP_IND='Y' or r.CPTY_CD='ICEU_BMOCMC_dummy')
and src_sys_cd not in ('GFI_CM') --exclude Bond Forwards