select
    sum(VM_NET_PAY_COLLECT) EXPSR_AMT,
    CPTY_CD,
    VM_NET_PAY_COLLECT_CCY CCY_CD
from SA_CCR.RF_CCP_MARGIN
where START_DT <= TO_DATE(?, 'YYYY-MM-DD')
and END_DT > TO_DATE(?, 'YYYY-MM-DD')
and DERIV_MRGN_IND = 'Y'
and VM_NET_PAY_COLLECT_CCY is not null
GROUP BY CPTY_CD, VM_NET_PAY_COLLECT_CCY