SELECT B.*, A.*
 FROM SA_CCR.POSITN A
 LEFT JOIN (SELECT POSITN_ID, BSKT_NUM, UNDRLY_SEC_SYMBOL, INIT_FIXG, WT FROM SA_CCR.TRADEREH_BSKT
 WHERE BUS_DT =to_date(?,'YYYY-MM-DD')) B
 --WHERE BUS_DT = '29 AUG 2018')
 ON A.POSITN_ID=B.POSITN_ID
 WHERE A.BUS_DT=to_date(?,'YYYY-MM-DD') AND A.EXPR_RUN_ID=99999999
 AND A.SRC_SYS_CD='NONCORE_IBG'